export const wideGalleryEntries = new Set(["fallen-valkyrie-technical-design", "water-blossoms", "sacred-forest", "hazy-city", "alien-landscape"]);

export const galleryCaptions: Record<string, [string, string]> = {
  "fallen-valkyrie-technical-design": ["Combat systems, boss AI and technical animation", "战斗系统、Boss AI 与技术动画"],
  "starshore-technical-design": ["Movement, abilities and gameplay systems", "移动、技能与玩法系统"],
  "grid-based-tactical-rpg-template": ["Grid tools, pathfinding and tactical gameplay", "网格工具、寻路与战术玩法"],
  "water-blossoms": ["Environment, lighting and procedural vegetation", "环境制作、灯光与程序化植被"],
  "sacred-forest": ["Stylized environment and custom Maya tools", "风格化环境与 Maya 工具开发"],
  "tenebria-character-rig": ["Character production, rigging and procedural hair", "角色制作、绑定与程序化毛发"],
  "vertex-normals-tool": ["Maya tool development and workflow design", "Maya 工具开发与工作流设计"],
  "cube-burst-vfx": ["Rigged animation and Niagara effects", "绑定动画与 Niagara 特效"],
  "homing-projectile-vfx": ["Realtime projectile effects", "实时弹体特效"],
  "stylized-classroom": ["Environment modeling, materials and lighting", "环境建模、材质与灯光"],
  "flintlock-pistol": ["Modeling, texturing and materials", "建模、贴图与材质"],
  "castle-town-lighting": ["Scene dressing, lighting and rendering", "场景布置、灯光与渲染"],
  "stylized-shrine": ["Modeling, sculpting and material work", "建模、雕刻与材质制作"],
  "abigail-williams-sculpt": ["Character sculpting", "角色雕刻"],
  "zelda-animation-studies": ["Character animation studies", "角色动画练习"],
  "mel-clockwork-platform": ["Mechanical animation driven entirely by MEL", "完全由 MEL 脚本驱动的机械动画"],
  "t14-armata": ["Hard-surface modeling and topology", "硬表面建模与拓扑"],
  "fantasy-vehicle": ["Hard-surface modeling and topology", "硬表面建模与拓扑"],
  "hazy-city": ["Environment concept and digital painting", "环境概念设计与数字绘画"],
  "sketchbook-studies": ["Perspective and form construction", "透视与形体构建"],
  "storyboard-master-studies": ["Shot composition and sequence studies", "镜头构图与分镜临摹"],
  "skyward-island-concept": ["Environment concept in ballpoint pen", "圆珠笔环境概念设计"],
  "hotel-room": ["Photo matching, lighting and rendering", "照片匹配、灯光与渲染"],
  "alien-landscape": ["Modeling and procedural scene assembly", "建模与程序化场景搭建"],
  "antique-tabletop": ["Still-life modeling, textures and lighting", "静物建模、贴图与灯光"],
  "misty-night": ["Texturing, lighting and compositing", "贴图、灯光与后期合成"],
  "dunes": ["Texturing, look development and rendering", "贴图、视觉开发与渲染"],
};
